### ISSUE TITLE
Issue with setup of USB device

### ISSUE THREAD

**Issue by IsomanGJ** [jovial/JFormica#5]
Just trying to setup on my PC. Have one ant stick plugged in which I know is working. Tried running a couple of demos but they fail on “new AntTransceiver(0);” part of line with

Exception in thread “main” java.lang.NullPointerException
at javax.usb.UsbHostManager.getServicesName(UsbHostManager.java:96)
at javax.usb.UsbHostManager.initialize(UsbHostManager.java:32)
at javax.usb.UsbHostManager.getUsbServices(UsbHostManager.java:24)
at org.cowboycoders.ant.interfaces.AntTransceiver.doInit(AntTransceiver.java:141)
at org.cowboycoders.ant.interfaces.AntTransceiver.(AntTransceiver.java:125)
at org.cowboycoders.ant.interfaces.AntTransceiver.(AntTransceiver.java:114)
at virtualride.AcknowledgedDemo.main(AcknowledgedDemo.java:196)

Any Ideas? Thanks   

Logged above on website and you asked me to put it here.  

You replied:
What operating system are you using? Does the
the vendorId, deviceId pair of your usb stick correspond to 0fcf and 1008 respectively

Answer:Windows 10
If I look at the device details device manager I see this: USB\VID_0FCF&PID_1009

which I suspect means it's 1009.

On the back of that tried 
new AntTransceiver(1)
and
new AntTransceiver(1009)

but got same effect.  Sorry - not exactly sure what value I'm supposed to be passing and can't find a document to tell me.

Thanks in advance

**Comment by jovial** [comment]
The zero in `new AntTransceiver(0)`  refers to how many devices to skip whilst walking through all of the enumerated devices; zero would just return the first one found. This is useful if you have multiple matching devices on the same machine. The list of devices that produce a match comes from [AntDeviceId](https://github.com/jovial/JFormica/blob/0cb827416e7b2fc66f1bda611c65c6dcdda0a50b/jformica_jsr80/src/main/java/org/cowboycoders/ant/interfaces/AntDeviceId.java). 

However, it doesn't look like it gets far enough to actually search for these devices. It looks like this is most likely a problem with [javaxusb](http://usb4java.org/). You might want to try a later version and report back if the behaviour changes.

**Comment by IsomanGJ** [comment]
HIi Jovial,  thanks for that.  Downloaded a newer version (didn't realise I had an older version) and that seemed to work.  Got errors further on but it got me over that one  at least.  Thanks

**Comment by IsomanGJ** [comment]
Like I said it gets a bit further but now falls over on the following:
USB error 3: Unable to claim interface: Access denied (insufficient permissions)

when I run: node.start();

Operating system is windows 10.  Thanks again in advance

**Comment by jovial** [comment]
I believe you have to follow this guide:

https://github.com/libusb/libusb/wiki/Windows#How_to_use_libusb_on_Windows

**Comment by IsomanGJ** [comment]
It does look to me like i have the latest driver and I know that the device does work as I use it through Zwift.  Anything else you can think of?  Thanks in advance

**Comment by IsomanGJ** [comment]
Hi Jovial,  Actually it did seem to work if I switched USB driver to libusdk from libusb.  So I think it's working now.  Thanks for your help
